Config = {

animateTextures = true, --DEIXE true PARA AS MODELS FICAR COM A ANIMAÇÃO MUDANDO DE CORES

animateSpeed = 500 --VELOCIDADE DE MUDANÇA DE CORES
--QUANTO MENOR A VELOCIDADE, MAIS RÁPIDO FICA A ANIMAÇÃO DE MUDANÇA DAS CORES

}