addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'dft-30.txd' ) 
engineImportTXD( txd, 413 ) 
dff = engineLoadDFF('dft-30.dff', 413 ) 
engineReplaceModel( dff, 413 )
end)