preguntas = {
	{"¿Está permitido el uso de multicuentas?", "Sí, no hay ningún problema", "No, me pueden sancionar IC", "No, me pueden sancionar OOC", 3},
	{"¿Qué son las siglas CK?", "Car Kill", "Character Kill", "Clan Kill", 2},
	{"Vas por la calle, es de noche. Alguien se te pone detrás con una pistola silenciada y te pide tu dinero, ¿qué harías?", "Le doy todo mi dinero", "Pregunto al staff para ver si tiene spec y si lo tiene continuo el rol", "Salgo huyendo dándole una patada y grito pidiendo auxilio", 2},
	{"A la hora de realizar un PK, ¿es necesario que haya un staff supervisándolo?", "Sí, puesto que puede haber problemas en el rol", "Sí, puesto que en caso contrario el PK no será válido", "No, ya que no hace falta supervisión para PK", 3},
	{"¿Qué es PG?", "Realizar acciones imposibles o que nunca harías en la vida real", "Realizar acciones imposibles o que nunca haría tu PJ", "Ambas respuestas son correctas", 2},
	{"Supongamos que vas conduciendo a más de 100 KM/H, te estrellas y te vas del lugar. ¿Qué regla habrias incumplido?", "NRC", "NRE", "NRH", 1},
	{"Estás en un rol y un usuario empieza a cortarlo por /b, ¿qué haces?", "Solicitar un /staff mediante /pm", "Evadir el rol y darlo por finalizado. ¡Es imposible rolear con ese user!", "Reportarlo en foro para que no vuelva a suceder", 3},
	{"A la hora de realizar un CK, ¿es necesario que haya un staff supervisándolo?", "Sí, puesto que puede haber problemas en el rol", "Sí, puesto que en caso contrario el CK no será válido", "No, ya que no hace falta supervisión para CK", 1},
	{"¿Qué caso se puede considerar MG?", "Confundir canales IC y OOC", "Obtener beneficio IC de información obtenida OOC", "Ambas respuestas son correctas", 2},
	{"Estás en low-hp. ¿Debes de rolear heridas?", "Sí, tengo que rolear heridas en este caso", "No, no tengo por qué rolearlo aunque si puedo si quiero", "No, y además no está permitido rolear heridas estando en low-hp", 1},
	{"¿Qué es CJ?", "Carl Johnson", "Car Jacking", "Ambas respuestas son correctas", 2},
	{"¿Qué es BA?", "Ban Automatic", "Bug Admin", "Bug Abuser", 3},
	{"¿Qué es IG?", "In Game", "In Gear", "No es un término de rol", 1},
	{"¿Cómo puedes actuar ante un staff que abusa?", "Reportándolo en foro con pruebas", "Enviando un MP en foro a un desarrollador con pruebas", "Acusar al staff de abusar en Discord", 1},
	{"¿Qué sucede si el presupuesto de una facción llega a 0?", "La faccción puede pedir un rescate de forma IC", "La facción puede de ser subastada de forma IC", "Ambas son correctas", 3},
	{"Selecciona la opción correcta", "/me se agacha y se ata los cordones", "/do se agacha y se ata los cordones", "/b se agacha y se ata los cordones", 1},
	{"Selecciona la opción incorrecta", "/do el vehículo estaría pintado de verde", "/me el vehículo estaría pintado de verde", "/intentar pintar el vehículo de verde", 1},
	{"¿Cómo puedes entrar en una facción oficial legal?", "Enviando un MP al líder via foro", "Realizando currículum en foro", "Intentando rolear con esa facción IG", 2},
	{"¿Cómo puedes entrar en una facción oficial ilegal?", "Enviando un MP al líder via foro", "Realizando currículum en foro", "Intentando rolear con esa facción IG", 3},
	{"¿Se puede salir de la zona de rol?", "Sí, se puede salir dado que no hay zona de rol", "Sí, pero previa autorización del staff", "No, no se puede salir de la zona de rol bajo ningún concepto", 3},
	{"Selecciona el nombre válido", "Roberto Linares", "roberto linares", "Roberto_Linares", 1},
	{"Vas al taller y el mecánico tiene prisa, así que te ofrece repararte sin rol ¿qué haces?", "Me voy del taller y espero a otro mecánico", "Le hago caso al mecánico y que me repare", "Acudo a foro a reportar al jugador por intento de evasión de rol", 3},
	{"¿Qué número se debe usar para avisar al Servicio de Emergencias?", "911", "112", "Ambas respuestas son correctas", 3},
	{"Selecciona la opción correcta", "/intentar tirar la moneda al aire y cogerla al vuelo", "/intentar quitarse las esposas con un clip", "/intentar sobrevivir al disparo del rifle", 1},
	{"El hecho de que un /intentar salga que sí, ¿implica que sea válido?", "Sí, ya que el /intentar es el que prevalece", "Sí, puesto que en caso contrario sería evasión de rol", "No, ya que en algunos casos se puede cometer faltas de rol", 3},
	{"¿Está permitido ceder / vender / prestar / intercambiar tu cuenta?", "Sí, siempre y cuando no haya ningún problema OOC", "No, y los que participen se irán baneados", "No, y las cuentas implicadas serán bloqueadas", 3},
}