addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD ( "landhub.txd" )
engineImportTXD ( txd, 11566 )
col = engineLoadCOL ( "hub5_grass.col" )
engineReplaceCOL ( col, 11566 )
dff = engineLoadDFF ( "hub5_grass.dff", 0 )
engineReplaceModel ( dff, 11566 )
engineSetModelLODDistance(11566, 999999)
end)
