function peti(nameb)
	--local nameb = exports.players:getCharacterID(player)
	local nameplayer = exports.sql:query_assoc( "SELECT `gordura` FROM `characters` WHERE `characterID` = " ..tostring(nameb))
	local facc = nameplayer[1]['gordura']
	--outputChatBox("tu gordura es " .. tostring(facc), player)
	--outputChatBox("tu id " .. tostring(nameb), player)
	outputChatBox("Recuerda Leer Conceptos De Rol ( Panel F1 )", player, 255, 165, 0)
		if facc == 1 then 
			setTimer(function()
				fac = "pd"
				bindeos(fac)
			end, 1000, 1)
		elseif facc == 2 then
			setTimer(function()
				fac = "ems"
				bindeos(fac)
			end, 1000, 1)
		elseif facc == 3 then
			setTimer(function()
				fac = "meca"
				bindeos(fac)
			end, 1000, 1)
		elseif facc == 4 then
			setTimer(function()
				fac = "ilegal"
				bindeos(fac)
			end, 1000, 1)
					
		end
end
--addCommandHandler("peti", peti)

function topeti()
	player = source
    setTimer(function()
		nameb = exports.players:getCharacterID(player)
		outputChatBox("", player)
		peti(nameb)
	end, 1000, 1)
end
addEventHandler("onPlayerSpawn", getRootElement(), topeti)
--addCommandHandler("peti", topeti)
  




function bindeos(fac)
	outputChatBox("Facción recibida: " .. tostring(fac), player)
	fac = tostring(fac)
	if fac == "pd" or fac == "ems" or fac == "meca" or fac == "ilegal" then
	
			unbindKey(player, "1", "down", "me saca su arma de su CT y la desenfunda.")
			unbindKey(player, "1", "down", "do .:Click-Clack:. Arma lista para usar")
			unbindKey(player, "2", "down", "me examina de pies a cabeza al sujeto")
			unbindKey(player, "2", "down", "do podria?")
			unbindKey(player, "3", "down", "me saca un cuchillo y destruye/corta cualquier objeto de comunicación")
			unbindKey(player, "3", "down", "do se vería el sujeto totalmente incomunicado")
			unbindKey(player, "4", "down", "me se retiene las heridas")
			unbindKey(player, "4", "down", "do aun tendría ánimos para continuar")
			unbindKey(player, "4", "down", "crack")
			unbindKey(player, "5", "down", "me saca unas esposas de su CT y las abre/cierra")
			unbindKey(player, "5", "down", "do se veria esposado/desesposado al sujeto")
			unbindKey(player, "6", "down", "me coge el megáfono de la silla, lo enciende y seguidamente habla por el.")
			unbindKey(player, "6", "down", "meg Le habla la policía nacional , por favor estacione su vehículo en la parte derecha de la carretera, apague el motor y espere las indicaciones.")
			unbindKey(player, "7", "down", "me abre/cierra la puerta de la patrulla")
			unbindKey(player, "7", "down", "do el sujeto entraria/saldria de la patrulla por si solo")
			unbindKey(player, "8", "down", "me agarra/suelta al sujeto y lo sube/baja de su hombro")
			unbindKey(player, "8", "down", "do se veria como se lo echa/baja de su hombro")
			unbindKey(player, "8", "down", "cargar")
			unbindKey(player, "9", "down", "me se soba su cabeza y continua conduciendo/viendo.")
			unbindKey(player, "9", "down", "do El cinturón/casco actuaría ante el choque.")
			unbindKey(player, "1", "down", "me le toma el pulso al sujeto")
			unbindKey(player, "1", "down", "do tendría pulso?")
			unbindKey(player, "2", "down", "me revisa todo el cuerpo en busca de heridas")
			unbindKey(player, "2", "down", "do que heridas tendría?")
			unbindKey(player, "3", "down", "me saca una pomada/yeso de su kit medico")
			unbindKey(player, "3", "down", "do se vería como aplica con cuidado el tratamiento para las heridas")
			unbindKey(player, "1", "down", "me Abre el capo del vehículo y lo observa detalladamente")
			unbindKey(player, "1", "down", "do Luego de 5 minutos encontraría un daño grave en el motor")
			unbindKey(player, "1", "down", "me Comienza a reparar el daño")
			unbindKey(player, "1", "down", "do Luego de 2 horas el motor quedaría reparado")
			unbindKey(player, "2", "down", "me Comienza a retirar la pieza que se encuentra dañada")
			unbindKey(player, "2", "down", "do Esta caería")
			unbindKey(player, "2", "down", "me Busca una nueva pieza, la pone en el vehículo y la aprieta")
			unbindKey(player, "2", "down", "do después de 1 hora terminaría la reparación")
			unbindKey(player, "3", "down", "me Toma su radio y llama a otros mecánicos")
			unbindKey(player, "3", "down", "me busca una lata de pintura con el color elegido por el cliente")
			unbindKey(player, "3", "down", "do Se vería a varios mecánicos pintar el vehículo (NPC)")
			unbindKey(player, "3", "down", "do Después de 3 horas el vehículo estaría pintado")
			unbindKey(player, "4", "down", "me Toma una computadora de la mesa y la conecta al vehiculo")
			unbindKey(player, "4", "down", "me Realiza la reprogramación del sistema del vehículo")
			unbindKey(player, "4", "down", "do Este tendría una mejora en la velocidad y la aceleración del vehículo")
			unbindKey(player, "4", "down", "do Después de 1 hora finalizaría el full Tuning")
			unbindKey(player, "5", "down", "me Toma el gato y levanta el vehículo y posteriormente con su cruceta destornilla la llanta")
			unbindKey(player, "5", "down", "me Busca una nueva llanta y la atornilla en su lugar")
			unbindKey(player, "5", "down", "do Esta quedaría firme")
			unbindKey(player, "5", "down", "do Después de 20 minutos finaliza el cambio de llanta")
			unbindKey(player, "6", "down", "me Toma sus herramientas y comienza a retirar el foco antiguo")
			unbindKey(player, "6", "down", "me Coloca un par de bombillos led nuevos en su lugar")
			unbindKey(player, "6", "down", "do Brillarían del color elegido por el cliente")
			unbindKey(player, "6", "down", "do Después de 15 minutos finaliza el cambio de luces")
			unbindKey(player, "1", "down", "me saca el arma de su cinturón y la desenfunda")
			unbindKey(player, "1", "down", "do ,;Click Clack ;, el arma estaría lista para disparar")
			unbindKey(player, "2", "down", "me examina de pies a cabeza al sujeto")
			unbindKey(player, "2", "down", "do podría?")
			unbindKey(player, "3", "down", "me saca un cuchillo y destruye/corta cualquier objeto de comunicación")
			unbindKey(player, "3", "down", "do se vería el sujeto totalmente incomunicado")
			unbindKey(player, "4", "down", "me se retiene las heridas")
			unbindKey(player, "4", "down", "do aun tendría ánimos para continuar")
			unbindKey(player, "4", "down", "crack")
			unbindKey(player, "5", "down", "g Levante las mano ahora mismo, esto es un robo")
			unbindKey(player, "6", "down", "me agarra/suelta al sujeto y lo sube/baja de su hombro")
			unbindKey(player, "6", "down", "do se veria como se lo echa/baja de su hombro")
			unbindKey(player, "6", "down", "cargar")
			unbindKey(player, "9", "down", "me se soba su cabeza y continua conduciendo/viendo.")
			unbindKey(player, "9", "down", "do El cinturón/casco actuaría ante el choque.")
		setTimer(function()
		if fac == "pd" then
		
			bindKey(player, "1", "down", "me saca su arma de su CT y la desenfunda.")
			bindKey(player, "1", "down", "do .:Click-Clack:. Arma lista para usar")
			bindKey(player, "2", "down", "me examina de pies a cabeza al sujeto")
			bindKey(player, "2", "down", "do podria?")
			bindKey(player, "3", "down", "me saca un cuchillo y destruye/corta cualquier objeto de comunicación")
			bindKey(player, "3", "down", "do se vería el sujeto totalmente incomunicado")
			bindKey(player, "4", "down", "me se retiene las heridas")
			bindKey(player, "4", "down", "do aun tendría ánimos para continuar")
			bindKey(player, "4", "down", "crack")
			bindKey(player, "5", "down", "me saca unas esposas de su CT y las abre/cierra")
			bindKey(player, "5", "down", "do se veria esposado/desesposado al sujeto")
			bindKey(player, "6", "down", "me coge el megáfono de la silla, lo enciende y seguidamente habla por el.")
			bindKey(player, "6", "down", "meg Le habla la policía nacional , por favor estacione su vehículo en la parte derecha de la carretera, apague el motor y espere las indicaciones.")
			bindKey(player, "7", "down", "me abre/cierra la puerta de la patrulla")
			bindKey(player, "7", "down", "do el sujeto entraria/saldria de la patrulla por si solo")
			bindKey(player, "8", "down", "me agarra/suelta al sujeto y lo sube/baja de su hombro")
			bindKey(player, "8", "down", "do se veria como se lo echa/baja de su hombro")
			bindKey(player, "8", "down", "cargar")
			bindKey(player, "9", "down", "me se soba su cabeza y continua conduciendo/viendo.")
			bindKey(player, "9", "down", "do El cinturón/casco actuaría ante el choque.")
			outputChatBox("Se han actualizado tus bnd para la Policía Nacional. teclas[1 al 9]", player, 0, 255, 0)
		elseif fac == "ems" then		
			b1 = bindKey(player, "1", "down", "me le toma el pulso al sujeto")
			bindKey(player, "1", "down", "do tendría pulso?")
			bindKey(player, "2", "down", "me revisa todo el cuerpo en busca de heridas")
			bindKey(player, "2", "down", "do que heridas tendría?")
			bindKey(player, "3", "down", "me saca una pomada/yeso de su kit medico")
			bindKey(player, "3", "down", "do se vería como aplica con cuidado el tratamiento para las heridas")
			bindKey(player, "3", "down", "do funcionaria?")

			outputChatBox("Se han actualizado tus bnd para EMS. teclas[1 al 3]", player, 0, 255, 0)
		elseif fac == "meca" then
		
			bindKey(player, "1", "down", "me Abre el capo del vehículo y lo observa detalladamente")
			bindKey(player, "1", "down", "do Luego de 5 minutos encontraría un daño grave en el motor")
			bindKey(player, "1", "down", "me Comienza a reparar el daño")
			bindKey(player, "1", "down", "do Luego de 2 horas el motor quedaría reparado")
			bindKey(player, "2", "down", "me Comienza a retirar la pieza que se encuentra dañada")
			bindKey(player, "2", "down", "do Esta caería")
			bindKey(player, "2", "down", "me Busca una nueva pieza, la pone en el vehículo y la aprieta")
			bindKey(player, "2", "down", "do después de 1 hora terminaría la reparación")
			bindKey(player, "3", "down", "me Toma su radio y llama a otros mecánicos")
			bindKey(player, "3", "down", "me busca una lata de pintura con el color elegido por el cliente")
			bindKey(player, "3", "down", "do Se vería a varios mecánicos pintar el vehículo (NPC)")
			bindKey(player, "3", "down", "do Después de 3 horas el vehículo estaría pintado")
			bindKey(player, "4", "down", "me Toma una computadora de la mesa y la conecta al vehiculo")
			bindKey(player, "4", "down", "me Realiza la reprogramación del sistema del vehículo")
			bindKey(player, "4", "down", "do Este tendría una mejora en la velocidad y la aceleración del vehículo")
			bindKey(player, "4", "down", "do Después de 1 hora finalizaría el full Tuning")
			bindKey(player, "5", "down", "me Toma el gato y levanta el vehículo y posteriormente con su cruceta destornilla la llanta")
			bindKey(player, "5", "down", "me Busca una nueva llanta y la atornilla en su lugar")
			bindKey(player, "5", "down", "do Esta quedaría firme")
			bindKey(player, "5", "down", "do Después de 20 minutos finaliza el cambio de llanta")
			bindKey(player, "6", "down", "me Toma sus herramientas y comienza a retirar el foco antiguo")
			bindKey(player, "6", "down", "me Coloca un par de bombillos led nuevos en su lugar")
			bindKey(player, "6", "down", "do Brillarían del color elegido por el cliente")
			bindKey(player, "6", "down", "do Después de 15 minutos finaliza el cambio de luces")
			outputChatBox("Se han actualizado tus bnd para MECA. teclas[1 al 6]", player, 0, 255, 0)
		elseif fac == "ilegal" then		
			bindKey(player, "1", "down", "me saca el arma de su cinturón y la desenfunda")
			bindKey(player, "1", "down", "do ,;Click Clack ;, el arma estaría lista para disparar")
			bindKey(player, "2", "down", "me examina de pies a cabeza al sujeto")
			bindKey(player, "2", "down", "do podría?")
			bindKey(player, "3", "down", "me saca un cuchillo y destruye/corta cualquier objeto de comunicación")
			bindKey(player, "3", "down", "do se vería el sujeto totalmente incomunicado")
			bindKey(player, "4", "down", "me se retiene las heridas")
			bindKey(player, "4", "down", "do aun tendría ánimos para continuar")
			bindKey(player, "4", "down", "crack")
			bindKey(player, "5", "down", "g Levante las mano ahora mismo, esto es un robo")
			bindKey(player, "6", "down", "me agarra/suelta al sujeto y lo sube/baja de su hombro")
			bindKey(player, "6", "down", "do se veria como se lo echa/baja de su hombro")
			bindKey(player, "6", "down", "cargar")
		    bindKey(player, "9", "down", "me se soba su cabeza y continua conduciendo/viendo")
			bindKey(player, "9", "down", "do El cinturón/casco actuaría ante el choque")
			outputChatBox("Se han actualizado tus bnd para ILEGAL. teclas[1 al 5]", player, 0, 255, 0)
			
		end
		end, 1000, 1)
	else
		outputChatBox("USA: /bnd [pd, ems, meca, ilegal]", 255, 0, 0)
    end
end

function actbind(play, c, id)
	player = play
	if id then
		if id == "pd" then
			ply = exports.players:getCharacterID(play)
			outputChatBox("Cargando Actualizacion de bnd", play, 0, 255, 0)
			exports.sql:query_free( "UPDATE `characters` SET `gordura` = 1 WHERE `characterID` =  " .. tostring(ply))
			fac = "pd"
			bindeos(fac)
		elseif id == "ems" then
			ply = exports.players:getCharacterID(play)
			outputChatBox("Cargando Actualizacion de bnd", play, 0, 255, 0)
			exports.sql:query_free( "UPDATE `characters` SET `gordura` = 2 WHERE `characterID` =  " .. tostring(ply))
			fac = "ems"
			bindeos(fac)
		elseif id == "meca" then
			ply = exports.players:getCharacterID(play)
			outputChatBox("Cargando Actualizacion de bnd", play, 0, 255, 0)
			exports.sql:query_free( "UPDATE `characters` SET `gordura` = 3 WHERE `characterID` =  " .. tostring(ply))
			fac = "meca"
			bindeos(fac)
		elseif id == "ilegal" then
			ply = exports.players:getCharacterID(play)
			outputChatBox("Cargando Actualizacion de bnd", play, 0, 255, 0)
			exports.sql:query_free( "UPDATE `characters` SET `gordura` = 4 WHERE `characterID` =  " .. tostring(ply))
			fac = "ilegal"
			bindeos(fac)
		else
			outputChatBox("No existe el bindeo, USA: /bnd [pd, ems, meca, ilegal]", play, 255, 0, 0)
		end		
	else
		outputChatBox("USA: /bnd [pd, ems, meca, ilegal]", play, 255, 0, 0)
    end
end

addCommandHandler("bnd", actbind)

function unbnd (pl)
	upl = exports.players:getCharacterID(pl)
	exports.sql:query_free( "UPDATE `characters` SET `gordura` = 0 WHERE `characterID` =  " .. tostring(upl))
	outputChatBox("Se han retirado tus bnd", pl, 255, 0, 0)
	
			unbindKey(player, "1", "down", "me saca su arma de su CT y la desenfunda.")
			unbindKey(player, "1", "down", "do .:Click-Clack:. Arma lista para usar")
			unbindKey(player, "2", "down", "me examina de pies a cabeza al sujeto")
			unbindKey(player, "2", "down", "do podria?")
			unbindKey(player, "3", "down", "me saca un cuchillo y destruye/corta cualquier objeto de comunicación")
			unbindKey(player, "3", "down", "do se vería el sujeto totalmente incomunicado")
			unbindKey(player, "4", "down", "me se retiene las heridas")
			unbindKey(player, "4", "down", "do aun tendría ánimos para continuar")
			unbindKey(player, "4", "down", "crack")
			unbindKey(player, "5", "down", "me saca unas esposas de su CT y las abre/cierra")
			unbindKey(player, "5", "down", "do se veria esposado/desesposado al sujeto")
			unbindKey(player, "6", "down", "me coge el megáfono de la silla, lo enciende y seguidamente habla por el.")
			unbindKey(player, "6", "down", "meg Le habla la policía nacional , por favor estacione su vehículo en la parte derecha de la carretera, apague el motor y espere las indicaciones.")
			unbindKey(player, "7", "down", "me abre/cierra la puerta de la patrulla")
			unbindKey(player, "7", "down", "do el sujeto entraria/saldria de la patrulla por si solo")
			unbindKey(player, "8", "down", "me agarra/suelta al sujeto y lo sube/baja de su hombro")
			unbindKey(player, "8", "down", "do se veria como se lo echa/baja de su hombro")
			unbindKey(player, "8", "down", "cargar")
			unbindKey(player, "9", "down", "me se soba su cabeza y continua conduciendo/viendo")
			unbindKey(player, "9", "down", "do El cinturón/casco actuaría ante el choque")
			unbindKey(player, "1", "down", "me le toma el pulso al sujeto")
			unbindKey(player, "1", "down", "do tendría pulso?")
			unbindKey(player, "2", "down", "me revisa todo el cuerpo en busca de heridas")
			unbindKey(player, "2", "down", "do que heridas tendría?")
			unbindKey(player, "3", "down", "me saca una pomada/yeso de su kit medico")
			unbindKey(player, "3", "down", "do se vería como aplica con cuidado el tratamiento para las heridas")
			unbindKey(player, "1", "down", "me Abre el capo del vehículo y lo observa detalladamente")
			unbindKey(player, "1", "down", "do Luego de 5 minutos encontraría un daño grave en el motor")
			unbindKey(player, "1", "down", "me Comienza a reparar el daño")
			unbindKey(player, "1", "down", "do Luego de 2 horas el motor quedaría reparado")
			unbindKey(player, "2", "down", "me Comienza a retirar la pieza que se encuentra dañada")
			unbindKey(player, "2", "down", "do Esta caería")
			unbindKey(player, "2", "down", "me Busca una nueva pieza, la pone en el vehículo y la aprieta")
			unbindKey(player, "2", "down", "do después de 1 hora terminaría la reparación")
			unbindKey(player, "3", "down", "me Toma su radio y llama a otros mecánicos")
			unbindKey(player, "3", "down", "me busca una lata de pintura con el color elegido por el cliente")
			unbindKey(player, "3", "down", "do Se vería a varios mecánicos pintar el vehículo (NPC)")
			unbindKey(player, "3", "down", "do Después de 3 horas el vehículo estaría pintado")
			unbindKey(player, "4", "down", "me Toma una computadora de la mesa y la conecta al vehiculo")
			unbindKey(player, "4", "down", "me Realiza la reprogramación del sistema del vehículo")
			unbindKey(player, "4", "down", "do Este tendría una mejora en la velocidad y la aceleración del vehículo")
			unbindKey(player, "4", "down", "do Después de 1 hora finalizaría el full Tuning")
			unbindKey(player, "5", "down", "me Toma el gato y levanta el vehículo y posteriormente con su cruceta destornilla la llanta")
			unbindKey(player, "5", "down", "me Busca una nueva llanta y la atornilla en su lugar")
			unbindKey(player, "5", "down", "do Esta quedaría firme")
			unbindKey(player, "5", "down", "do Después de 20 minutos finaliza el cambio de llanta")
			unbindKey(player, "6", "down", "me Toma sus herramientas y comienza a retirar el foco antiguo")
			unbindKey(player, "6", "down", "me Coloca un par de bombillos led nuevos en su lugar")
			unbindKey(player, "6", "down", "do Brillarían del color elegido por el cliente")
			unbindKey(player, "6", "down", "do Después de 15 minutos finaliza el cambio de luces")
			unbindKey(player, "1", "down", "me saca el arma de su cinturón y la desenfunda")
			unbindKey(player, "1", "down", "do ,;Click Clack ;, el arma estaría lista para disparar")
			unbindKey(player, "2", "down", "me examina de pies a cabeza al sujeto")
			unbindKey(player, "2", "down", "do podría?")
			unbindKey(player, "3", "down", "me saca un cuchillo y destruye/corta cualquier objeto de comunicación")
			unbindKey(player, "3", "down", "do se vería el sujeto totalmente incomunicado")
			unbindKey(player, "4", "down", "me se retiene las heridas")
			unbindKey(player, "4", "down", "do aun tendría ánimos para continuar")
			unbindKey(player, "4", "down", "crack")
			unbindKey(player, "5", "down", "g Levante las mano ahora mismo, esto es un robo")
			unbindKey(player, "6", "down", "me agarra/suelta al sujeto y lo sube/baja de su hombro")
			unbindKey(player, "6", "down", "do se veria como se lo echa/baja de su hombro")
			unbindKey(player, "6", "down", "cargar")
			unbindKey(player, "9", "down", "me se soba su cabeza y continua conduciendo/viendo")
			unbindKey(player, "9", "down", "do El cinturón/casco actuaría ante el choque")
end
addCommandHandler("unbnd", unbnd)