addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'ByNatasha.txd' ) 
engineImportTXD( txd, 85 ) 
dff = engineLoadDFF('ByNatasha.dff', 85) 
engineReplaceModel( dff, 85 )
end)