addEventHandler('onClientResourceStart',resourceRoot,function () 
txd = engineLoadTXD( 'sanchez.txd' ) 
engineImportTXD( txd, 468 ) 
dff = engineLoadDFF('sanchez.dff', 468) 
engineReplaceModel( dff, 468 )
end)